# Generated by Django 4.0.1 on 2023-07-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_remove_quesmodel_id_quesmodel_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='Img',
        ),
    ]
